name: npm-publish
# on:
#   create:
#     tags:
#       - v*
jobs:
  build:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [  12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        # npm ci --if-present
        npm run build --if-present
        npm test
      env:
        CI: true
  publish:
    needs: build
    name: Publish new version to NPM
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
        # create_tag: "true"
        - run: yarn publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}